Name:           ros-indigo-soem-master
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS soem_master package

Group:          Development/Libraries
License:        LGPL
URL:            http://wiki.ros.org/soem_master
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-rtt
Requires:       ros-indigo-soem
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-rtt
BuildRequires:  ros-indigo-soem

%description
soem_master contains a C++ wrapper around soem_core, a factory object to
register and create drivers and a RTT component that will automatically create
the drivers and their services for all the slave for which a driver is known.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Jan 27 2015 Ruben Smits <ruben@intermodalics.eu> - 0.1.1-0
- Autogenerated by Bloom

* Mon Jan 26 2015 Ruben Smits <ruben@intermodalics.eu> - 0.1.0-0
- Autogenerated by Bloom

